"""Emit GitHub Actions workflow annotations for security findings."""

from __future__ import annotations

from typing import Any

from .settings import Settings

_SEVERITY_TO_LEVEL: dict[str, str] = {
    "HIGH": "error",
    "MEDIUM": "warning",
    "LOW": "notice",
}
_SEVERITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}


def _escape(text: str) -> str:
    """Escape workflow-command message data."""
    return text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def _escape_property(text: str) -> str:
    """Escape a workflow-command property value (file=...), where ':' and ',' are separators."""
    return _escape(text).replace(":", "%3A").replace(",", "%2C")


def emit_annotations(
    bandit_report: dict[str, Any],
    pip_audit_report: list[dict[str, Any]],
    settings: Settings,
    pip_audit_error: str = "",
    bandit_error: str = "",
) -> None:
    """Print GitHub Actions workflow commands to stdout.

    These produce inline annotations on the PR 'Files changed' tab (for bandit,
    which has file+line) and summary-level annotations (for pip-audit).
    No email notifications are generated by annotations.
    """
    if "bandit" in settings.enabled_tools:
        if bandit_error:
            print(f"::error::bandit did NOT run: {_escape(bandit_error)}")
        elif bandit_report.get("files_read", 0) is None:
            print(
                "::warning::bandit reported no file metrics, so the scanned file count is unknown"
            )
        results: list[dict[str, Any]] = bandit_report.get("results", [])

        def _sort_key(r: dict[str, Any]) -> int:
            return _SEVERITY_ORDER.get(r.get("issue_severity", "LOW"), 2)

        for result in sorted(results, key=_sort_key):
            sev = result.get("issue_severity", "LOW")
            level = _SEVERITY_TO_LEVEL.get(sev, "notice")
            fname = _escape_property(result.get("filename", ""))
            line = result.get("line_number", 0)
            test_id = result.get("test_id", "")
            text = _escape(result.get("issue_text", ""))
            print(f"::{level} file={fname},line={line}::[{test_id}] {text}")

    if "pip-audit" in settings.enabled_tools:
        if pip_audit_error:
            print(f"::error::pip-audit did NOT run: {_escape(pip_audit_error)}")
        elif not any("skip_reason" not in pkg for pkg in pip_audit_report):
            print("::warning::pip-audit audited 0 dependencies, so nothing was checked")
        for pkg in pip_audit_report:
            if not pkg.get("vulns"):
                continue
            name = pkg.get("name", "")
            version = pkg.get("version", "")
            for vuln in pkg["vulns"]:
                vid = vuln.get("id", "")
                fix = ", ".join(vuln.get("fix_versions", [])) or "no fix available"
                print(f"::warning::pip-audit: {name}@{version} — {vid} (fix: {fix})")
