"""Emit GitHub Actions workflow annotations for security findings."""

from __future__ import annotations

from typing import Any

from .settings import Settings

_SEVERITY_TO_LEVEL: dict[str, str] = {
    "HIGH": "error",
    "MEDIUM": "warning",
    "LOW": "notice",
}
_SEVERITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}


def emit_annotations(
    bandit_report: dict[str, Any],
    pip_audit_report: list[dict[str, Any]],
    settings: Settings,
) -> None:
    """Print GitHub Actions workflow commands to stdout.

    These produce inline annotations on the PR 'Files changed' tab (for bandit,
    which has file+line) and summary-level annotations (for pip-audit).
    No email notifications are generated by annotations.
    """
    if "bandit" in settings.enabled_tools:
        results: list[dict[str, Any]] = bandit_report.get("results", [])

        def _sort_key(r: dict[str, Any]) -> int:
            return _SEVERITY_ORDER.get(r.get("issue_severity", "LOW"), 2)

        for result in sorted(results, key=_sort_key):
            sev = result.get("issue_severity", "LOW")
            level = _SEVERITY_TO_LEVEL.get(sev, "notice")
            fname = result.get("filename", "")
            line = result.get("line_number", 0)
            test_id = result.get("test_id", "")
            text = (
                result.get("issue_text", "")
                .replace("%", "%25")
                .replace("\r", "%0D")
                .replace("\n", "%0A")
            )
            print(f"::{level} file={fname},line={line}::[{test_id}] {text}")

    if "pip-audit" in settings.enabled_tools:
        for pkg in pip_audit_report:
            if not pkg.get("vulns"):
                continue
            name = pkg.get("name", "")
            version = pkg.get("version", "")
            for vuln in pkg["vulns"]:
                vid = vuln.get("id", "")
                fix = ", ".join(vuln.get("fix_versions", [])) or "no fix available"
                print(f"::warning::pip-audit: {name}@{version} — {vid} (fix: {fix})")
